### ISSUE TITLE
Consider exporting all types.

### ISSUE THREAD

**Issue by LegNeato** [AlbertBrand/openapi-flowtype-definition#1]
This is a great project! I have some OpenAPI generators I want to use with this and it would be really awesome if I could strongly type the sub-objects while I build up the complete OpenAPI-typed object. Any thoughts on exporting more than just `OpenAPI`?

**Comment by LegNeato** [comment]
Friendly poke 👉 @AlbertBrand

**Comment by AlbertBrand** [comment]
Sorry, I missed your initial comment. I think it's possible to import any export from the subdirectory, f.i. `import type { Tags } from 'openapi-flowtype-definitions/src/Tags'`. If it doesn't I can re-export all types from the root.
